apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  imagePullSecrets:
    - name: regcred
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:  
  - name: main-container
    image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "while true; do ping -c4 google.com >> /var/log/index-input.html; sleep 10;done"]
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  - name: sidecar-container
    image: busybox # splunk adapter to ship the logs
    resources:
      limits:
        cpu: "10m"
        memory: "10Mi"
    command: ["/bin/sh"]
    args: ["-c", "while true; do cat /var/log/index-input.html > /tmp/index-output.html; sleep 60;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
