apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - image: brainupgrade/docker:20-dind
        name: docker
        securityContext:
          privileged: true        