apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
    - name: demo
      image: nginx
      resources:
        limits:
          cpu: "10m"
          memory: "20Mi"
      env:
        - name: PLAYER_INITIAL_LIVES 
          valueFrom:
            configMapKeyRef:
              name: cm-game-demo           
              key: player_initial_lives 
      volumeMounts:
      - name: config
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: cm-game-demo
        items:
        - key: "game.properties"
          path: "game.properties"
        - key: "user-interface.properties"
          path: "user-interface.properties"
