apiVersion: batch/v1
kind: Job
metadata:
  name: migration-task
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 100
  parallelism: 10
  template:
    spec:
      containers:
      - name: cron-job
        image: busybox
        args:
        - /bin/sh
        - -c
        - date; echo Migrating data to reporting server...;sleep 1;
      restartPolicy: Never
