apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: rajesh.brainupgrade.in
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  tls:
  - hosts:
    - rajesh.brainupgrade.in
    secretName: rajesh.brainupgrade.in
  rules:
    - host: rajesh.brainupgrade.in
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: weather-front
              servicePort: 8080
          - path: /site?(.*)
            backend:
              serviceName: wordpress
              servicePort: 8080
          - path: /api/v3/?(.*)
            backend:
              serviceName: api-v3
              servicePort: 8080             
          - path: /logger/?(.*)
            backend:
              serviceName: logger
              servicePort: 80                           
          - path: /hello/?(.*)
            backend:
              serviceName: hello
              servicePort: 80 
          - path: /video/?(.*)
            backend:
              serviceName: video
              servicePort: 8080
          - path: /messaging/?(.*)
            backend:
              serviceName: messaging
              servicePort: 8080
