apiVersion: apps/v1
kind: Deployment
metadata:
  name: facebook-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: facebook
      release: v1
  template:
    metadata:
      labels:
        app: facebook
        release: v1
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: facebook-app
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
          limits:
            cpu: 4m
            memory: 4Mi
          requests:
            cpu: 4m
            memory: 4Mi  
