apiVersion: v1
kind: Secret
metadata:
  name: db
data:
  password: cGFzc3dvcmQ=
  spring.datasource.url: amRiYzpteXNxbDovL2RiLXNlcnZlcjozMzA2L2FwcA==
  username: YWRtaW4=

# kubectl create secret generic db --from-literal=spring.datasource.url=jdbc:mysql://db-server:3306/app --from-literal=username=admin --from-literal=password=password  --dry-run -oyaml