apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-dynamic
  labels:
    app: nginx
spec:
  # storageClassName: storageclass-generic
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
