apiVersion: v1
kind: Service
metadata:
  name: headless
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  clusterIP: None
  selector:
    app: api-v1
# k run test2 --image radial/busyboxplus:curl -- tail -f /dev/null
# k exec test2 -- nslookup headless    