apiVersion: v1
kind: Pod
metadata:
  labels:
    release: qa
  name: tolerations-release-qa
spec:
  containers:
  - image: nginx
    name: nginx
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
    - key: "release"
      operator: "Exists"
      value: "qa"
      effect: "NoSchedule"

# kubectl get nodes -o json | jq ".items[]|{name:.metadata.name,taints:.spec.taints}"