# Monolith containing all app components 
# including database
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rajesh
  name: monolith
spec:
  containers:
  - image: brainupgrade/weather:monolith
    name: monolith
  restartPolicy: Always
