apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-load-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-load-test
  template:
    metadata:
      labels:
        app: cluster-load-test
    spec:
      imagePullSecrets:
        - name:  regcred
      containers:
      - image: brainupgrade/weather:monolith
        name: weather
        ports:
        - containerPort: 80
          name: web        
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "150m"
            memory: "1024Mi"
## test script pod
# kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://cluster-load-test; done"
# kubectl run -i --tty load-generator --rm --image=busybox --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://nginx; done"
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-load-test
spec:
  selector:
    app: cluster-load-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
